services:
  backend:
    image: go-to-do-server:${VERSION:-latest}
    build:
      context: ./go-server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: go-server
    restart: always
    environment:
      - PORT=8080
      - DB_URI=${DB_URI:-mongodb+srv://divadb:divadbuser@divadb.kzthfni.mongodb.net/?appName=divadb}
      - DB_NAME=${DB_NAME:-divadb}
      - DB_COLLECTION_NAME=${DB_COLLECTION_NAME:-todolist}
    networks:
      - app-network

  frontend:
    image: go-to-do-client:${VERSION:-latest}
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=http://localhost:8080
    ports:
      - "3000:8080"
    container_name: react-client
    restart: always
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
