[build]
  base = "client"
  command = "npm run build"
  publish = "client/build"

[build.environment]
  NODE_OPTIONS = "--openssl-legacy-provider"
  REACT_APP_API_URL = "https://tugas-cc-480903.de.r.appspot.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
